#!/usr/bin/env sh
# Print the Homebrew formula for a released version.
#
# Reads the checksums a release published, so the formula can never claim a
# hash nobody verified:
#
#   ./generate.sh 0.1.0 dist/SHA256SUMS > shlane.rb
#
# SHA256SUMS is "<sha256>  shlane-<version>-<target>.tar.gz" per line, which is
# what the release workflow uploads.
set -eu

version="${1:?usage: generate.sh <version> <SHA256SUMS>}"
sums="${2:?usage: generate.sh <version> <SHA256SUMS>}"
repo="${SHLANE_REPO:-prongbang/shlane}"

sum_for() {
    target="$1"
    line=$(grep "shlane-${version}-${target}.tar.gz" "$sums" || true)
    if [ -z "$line" ]; then
        echo "no checksum for ${target} in ${sums}" >&2
        exit 1
    fi
    echo "$line" | awk '{print $1}'
}

url_for() {
    echo "https://github.com/${repo}/releases/download/v${version}/shlane-${version}-$1.tar.gz"
}

# Resolved before the formula is printed: a failure inside the heredoc's
# command substitution would otherwise be swallowed and produce a formula with
# an empty sha256 in it.
mac_arm_sum=$(sum_for aarch64-apple-darwin)
mac_intel_sum=$(sum_for x86_64-apple-darwin)
linux_arm_sum=$(sum_for aarch64-unknown-linux-gnu)
linux_intel_sum=$(sum_for x86_64-unknown-linux-gnu)

cat <<EOF
# Generated by packaging/homebrew/generate.sh -- do not edit by hand.
class Shlane < Formula
  desc "fastlane-like build automation in a single binary"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$(url_for aarch64-apple-darwin)"
      sha256 "${mac_arm_sum}"
    end

    on_intel do
      url "$(url_for x86_64-apple-darwin)"
      sha256 "${mac_intel_sum}"
    end
  end

  on_linux do
    on_arm do
      url "$(url_for aarch64-unknown-linux-gnu)"
      sha256 "${linux_arm_sum}"
    end

    on_intel do
      url "$(url_for x86_64-unknown-linux-gnu)"
      sha256 "${linux_intel_sum}"
    end
  end

  def install
    bin.install "shlane"
    generate_completions_from_executable(bin/"shlane", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shlane --version")

    (testpath/"shlane.yaml").write <<~YAML
      lanes:
        hello:
          steps:
            - run: echo from-the-formula
    YAML
    assert_match "from-the-formula", shell_output("#{bin}/shlane run hello")
  end
end
EOF
